FROM python:3.12-slim
WORKDIR /app
ENV PYTHONPATH=/app
ENV MIGRATOR_ONLY=1
COPY pyproject.toml /app/
COPY poetry.lock* /app/
RUN pip install "poetry==2.2.1" && poetry config virtualenvs.create false && poetry install --without dev
COPY app /app/app
COPY alembic.ini /app/
COPY alembic /app/alembic
COPY migrator_alembic /app/migrator_alembic
CMD ["python", "-m", "app.migrator.main"]
